### ISSUE TITLE
Building layer not displayed in correct order on construction

### ISSUE THREAD

**Issue by homoroselaps** [jsettlers/settlers-remake#486] opened 2016-06-23 08:12 UTC
The two different layers of a building sometimes appear in the wrong order. This order changes sometimes while camera moves.
![settlersbug2buildingslayers](https://cloud.githubusercontent.com/assets/7871498/16296108/cd777f72-392a-11e6-9a59-71f4e3e34f75.png)

**Comment by abledbody** [comment] 2016-06-25 14:10
Duplicate of #225

**Closed** 2016-06-25 21:42 UTC
Labels: bug (minor), duplicate, user interface
