### ISSUE TITLE
Can't place mine, though place is free

### ISSUE THREAD

**Issue by derfuhrer2007** [jsettlers/settlers-remake#403] opened 2016-05-03 15:20 UTC
For some reasons it won't allow me to place this mine
[2016-05-03_20-23-10_mountain_lake.zip](https://github.com/jsettlers/settlers-remake/files/247188/2016-05-03_20-23-10_mountain_lake.zip)
![screenshot 7](https://cloud.githubusercontent.com/assets/18621498/14988251/b17fc63a-1170-11e6-8c01-f37f9ac3b1bf.png)

**Comment by derfuhrer2007** [comment] 2016-05-03 15:22
Probably it is not all in green, but the cursor was on a green dot.

**Comment by andreas-eberle** [comment] 2016-05-05 13:28
I think this is a duplicate of #253. Therefore I'm closing this one.

**Closed by andreas-eberle** 2016-05-05 13:28 UTC
