### ISSUE TITLE
Android no building icons

### ISSUE THREAD

**Issue by aligator** [jsettlers/settlers-remake#208] opened 2015-10-21 04:34 UTC
Alpha v. 0.1.3
![Uploading Screenshot_2015-10-21-06-30-08.png…]()

**Comment by aligator** [comment] 2015-10-21 04:42
aligator123.de/Screenshot_2015-10-21-06-30-08.png

I use android 5.1.1

**Comment by DerKrawallkeks** [comment] 2015-12-27 16:40
Hey. I'm new to github, sorry if I comment some stupid things. Just wanted to report the same issue, pc works fine, on Android (5.1.1)  looks exactly like on Adzwooly's screenshot.
I'm pretty sure it worked on my old phone, with the previous build of jsettlers on Android 4.1.2 (I'll check again)

**Comment by andreas-eberle** [comment] 2015-12-28 17:13
Hey guys,

thanks for your report. Did you only try the release version? Or did you also try to compile and start the current master? 
I just tested the current master with my Galaxy S6 and it works with this version. As I'm planning to release a new version during the next days, you'll probably get a fixed version then.

Best regards.

**Comment by DerKrawallkeks** [comment] 2015-12-28 21:29
Okay, sounds good. I'm not into Java, so I only used the released version. 
Therefore I'm really looking forward to another release version:)

**Comment by DerKrawallkeks** [comment] 2016-01-10 20:29
The problem is still there on the newest release-version (0.2). I'm wondering about one thing: when I select one building on the map, on the top left corner there's the buildings right symbol. Since I can't work with the sourcecode, I can't do research on that, but I thought it probably uses the same file. 
Therefore, it shouldn't be too difficult to solve the problem. Please someone do it;) It would make the Android version much more playable

**Comment by DerKrawallkeks** [comment] 2016-01-11 13:22
Works fine on Samsung Galaxy S4 (Android 5.0.1), but does not on Sony Xperia Z3 (Android 5.1.1)
Interesting!..

**Comment by andreas-eberle** [comment] 2016-01-13 10:49
It also works on my Galaxy S6. @michaelzangl: Do you have an idea what could cause this?

**Comment by aligator** [comment] 2016-01-18 16:49
No.

I would try to do some debuging, but I'm not very experienced With android development.

Yesterday I tried to setup the workspace, but I couldn't get it working.(some time ago I got it, but I don't have this workspace anymore...)

**Comment by andreas-eberle** [comment] 2016-01-18 22:58
I was able to reproduce it on a tablet. Unfortunately I cannot access it atm. @michaelzangl: Can you reproduce it with one of the tablets you have?

**Comment by michaelzangl** [comment] 2016-01-19 09:18
This happens when the app was not correctly packed. I am currently working on a new system to add those icons, it should not be a problem when that is finished.

**Comment by DerKrawallkeks** [comment] 2016-01-19 16:19
Okay great, looking forward to it!

**Comment by writeitstudios** [comment] 2016-03-31 06:22
Remains an issue on tablets - I'm using the Galaxy Tab A (T-555) and the building icons are not being shown either.

**Comment by michaelzangl** [comment] 2016-04-04 22:52
Fixed in #337

**Comment by DerKrawallkeks** [comment] 2016-04-06 10:59
@michaelzangl Thank you! How can I get a ready-to-go apk file to test it? I'm not into git or java programming, but I'd like to test it, since I've had the same problem

**Comment by michaelzangl** [comment] 2016-04-06 12:02
Compiling for android is difficult since it uses the outdated eclipse tools.

I created a short guide in https://github.com/jsettlers/settlers-remake/wiki/Setting-up-%28eclipse%29

**Comment by DerKrawallkeks** [comment] 2016-04-06 22:06
Okay, thx

**Comment by michaelzangl** [comment] 2016-04-06 22:14
Now there is a simpler way:
```
git clone https://github.com/jsettlers/settlers-remake.git
cd settlers-remake
git fetch
git checkout android-gradle
./gradlew runAndroid
```

This gradle build process is still in a rough alpha stage, let me know if you have any issues.

(For playing on PC: `./gradlew run`)

**Comment by andreas-eberle** [comment] 2016-04-23 15:33
I still have no building icons on android with the current master (now containing the gradle build).

**Comment by BlankFX1** [comment] 2017-02-24 13:35
It's 2017 and this bug still persists even with the nightlies.
If it can't be fixed, why not at least create a workaround?
I personally would be fine with a simple text list with the names of the buildings to click/tap on.

**Comment by andreas-eberle** [comment] 2017-03-05 11:46
@BlankFX1: The problem with this bug is that it does work on some devices but not on all. So its kind of hard to track down. Furthermore we aren't many people currently actively developing this game. You're welcome to help if you can...

However, the good news is that @Sylapse is currently working on a complete rework of the Android App in PR #532. With that, the bug should be fixed and the Android App become much more playable.

**Comment by andreas-eberle** [comment] 2017-05-28 12:12
@all: can you test again if this is fixed now with the new Android UI (test with the latest nightly builds from master).

**Closed** 2017-07-22 16:52 UTC
Labels: android, bug (critical)
