### ISSUE TITLE
Prefer platform-independent file paths

### ISSUE THREAD

**Issue by nevson** [jsettlers/settlers-remake#67] opened 2015-05-03 09:59 UTC
Hi, when running jsettlers directly under windows it fails finding the gfx and sound folder due to invalid path joining, [see here](https://github.com/jsettlers/settlers-remake/blob/48fe9246f77bbf2d823a79e6715c63201f464278/jsettlers.graphics.swing/src/jsettlers/graphics/swing/resources/ConfigurationPropertiesFile.java#L71). It creates a file paths which are looking like `C\:\\...\\JSettlers/Gfx` so the path contains invalid characters.

I'd recommend to use `Paths.get()` to join paths and return a `Path[]` array instead of a `String[]` array. E.g.:
```java
result[resultIdx++] = Paths.get(settlersFolder[folderIdx], subfolders[subfolderIdx]);
```
This way you could [replace these kind of checks](https://github.com/jsettlers/settlers-remake/blob/48fe9246f77bbf2d823a79e6715c63201f464278/jsettlers.graphics.swing/src/jsettlers/graphics/swing/resources/SwingResourceLoader.java#L67) against following generic file check:
```java
hasSndDir = hasSndDir || Files.exists(sndFolder.resolve("Siedler3_00.dat"));
```

In case you need to get the File object due to some legacy code, you can get it via `path.toFile()`. But generally it's recommended to use the newer Path class over the legacy File class.

**Comment by andreas-eberle** [comment] 2015-05-03 16:31
Hi @nevson,

in general you're right. However, afaik Android does not support / provide the Path class and most of the other java nio stuff. So when changing to the Path classes, we need to ensure that the game logic, which is shared between the Android and other OS' version, does not contain the Java nio code.

**Comment by nevson** [comment] 2015-05-04 10:45
@andreas-eberle Oh ok, didn't know that Android is so far behind regarding the nio stuff. Maybe you could polyfill parts of `Paths`/`Path` and `Files` class so that once they're available you can easily switch to them? E.g.:

```java
public final class Paths {
  private Paths() { }
  public static Path get(String parent, String child) {
    return new Path(new File(parent, child));
  }
 // ...
}

public class Path {
  private Path(File) { /*...*/ }
  public Path resolve(String other) {
    // Use File(parent, other) to resolve the file path...
  }
 // ...
}

// Files ...
```

But anyhow it'd be great if at least the issue with Windows caused by [this line](https://github.com/jsettlers/settlers-remake/blob/48fe9246f77bbf2d823a79e6715c63201f464278/jsettlers.graphics.swing/src/jsettlers/graphics/swing/resources/ConfigurationPropertiesFile.java#L71) could be fixed.

**Comment by andreas-eberle** [comment] 2015-05-05 14:32
@nevson: I just had a closer look at your first post again. I think there are some misunderstandings.

* You say `C\:\\...\\JSettlers/Gfx` would be an invalid path due to invalid path joining. That's not correct. Java supports mixing up backslahes and slashes in a path. So that's no issue here.
* You seem to have configured `settlers-folder` with the path to your JSettlers installation. However, this property needs the path to your original "The Settlers III" installation (which is containing the GFX and SND folders). I guess the path couldn't be resolved, as you don't have a GFX folder in your JSettlers directory.
* I work with a Windows PC and was not able to reproduce this problem. Does it work when changing the `settlers-folder` property? If not, please just delete your config.prp file and start the game with the newest release. A dialog should pop up and ask you to select the folder of your original Settlers III installation.

Best regards

**Comment by nevson** [comment] 2015-05-05 14:47
@andreas-eberle Sorry for the confusion. I've manually copied the gfx folder into the JSettlers folder so that it exists there.

Mhh I see, `C\:\\...\\JSettlers/Gfx` would have been a valid path. Then I'm wondering why it didn't work on my machine (Win7 64bit). I'm 100% positive that while debugging `new File(gfxFolder, "siedler3_00.7c003e01f.dat").exists()` returned always false. Then I've locally patched to code as described in my first post and then it worked for me. I'll do some more tests with the none patched code to see if I can track down the bug.

Btw. it seems like the Amazon demo GFX files have now a different name... it's no longer `7c003e01f` but the resource loader tries to search for a `siedler3_00.7c003e01f.dat` file (I've just manually extracted the content of the installer instead of executing it as the installer always failed).

**Comment by nevson** [comment] 2015-05-09 07:57
@andreas-eberle Not sure why but on my system Java seems to be sensible against slashes vs backslashes :( So `C:\...\settlers-demo/gfx` won't work but `C:\...\settlers-demo\gfx` works. Following patched helped in my case
```java
result[resultIdx++] = settlersFolder[folderIdx].replaceFirst("\\" + File.separator + "?$",
  "\\" + File.separator + subfolders[subfolderIdx]);
```
This should also work on Android, Linux, ... etc. Btw. I'm using jdk1.8.0_45 (32-bit) on Win7

Regarding the different gfx file names. Can you confirm that they've changed or did I get the wrong Amazon demo...?

**Comment by andreas-eberle** [comment] 2015-05-09 14:23
Do you only have a 32bit JVM or also a 32bit Win7 installation? If you have a 64bit Win7, please try to run the code with a 64bit JVM.
Anyway, it's very strange, as I also have a Win7 and JDK8. The only difference I can see is that I have both as 64bit versions.

Regarding the different naming of the grafics files: I can confirm this and openend #79.

**Comment by nevson** [comment] 2015-05-09 15:27
I've installed now also the 64bit version and suddenly it accepts the paths with slashes :/ Most surprisingly if I switch now back to 32bit then it also accetps the slashes... maybe I've now some weired system configuration. But I think it would be safer to use the variant with the `File.seperator`.

**Comment by nevson** [comment] 2015-05-09 15:44
Nope, I've to correct my last comment. To make sure that my local build is not the reason for this behavior I've downloaded the latest release and tested it with that. There I get the same error again

```bash
C:\Users\Nevson\development\JSettlers_v0.1.2-aplha>java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

C:\Users\Nevson\development\JSettlers_v0.1.2-aplha>java -jar JSettlers.jar
Exception in thread "main" SettlersDirectoryException [expectedSnds=[C:\Users\Ne
vson\development\JSettlers/SND, C:\Users\Nevson\development\JSettlers/snd, C:\Users\Nev
son\development\JSettlers/Snd], expectedGfxs=[C:\Users\Nevson\development\JSettlers/GFX,
C:\Users\Nevson\development\JSettlers/gfx, C:\Users\Nevson\development\JSettlers/Gfx], b
adVersion=true]
        at jsettlers.graphics.swing.resources.SwingResourceLoader.testConfig(Swi
ngResourceLoader.java:61)
        at jsettlers.graphics.swing.resources.SwingResourceLoader.setupGraphicsA
ndSoundResources(SwingResourceLoader.java:25)
        at jsettlers.main.swing.SwingManagedJSettlers.setupResourceManagers(Swin
gManagedJSettlers.java:117)
        at jsettlers.main.swing.SwingManagedJSettlers.main(SwingManagedJSettlers
.java:58)
```

**Comment by andreas-eberle** [comment] 2015-06-11 16:16
I close this, as it seems fixed.

**Closed by andreas-eberle** 2015-06-11 16:16 UTC
