### ISSUE TITLE
Ran out of carriers

### ISSUE THREAD

**Issue by derfuhrer2007** [jsettlers/settlers-remake#503] opened 2016-10-05 07:15 UTC
Seems that there is no reserve of carriers kept, thing which leads to a jam in construction

[2016-10-05_09-46-34_448_2Ph,M.plateau_replay.zip](https://github.com/jsettlers/settlers-remake/files/510262/2016-10-05_09-46-34_448_2Ph.M.plateau_replay.zip)

**Comment by andreas-eberle** [comment] 2016-10-05 15:33
Closing, as this is a duplicate of #120.

**Closed by andreas-eberle** 2016-10-05 15:33 UTC
