### ISSUE TITLE
Forester plants in a strange pattern

### ISSUE THREAD

**Issue by derfuhrer2007** [jsettlers/settlers-remake#392] opened 2016-04-30 16:44 UTC
Just starting the small island map and forester seems to plant in a line, with the latest planted at the margin of it's range, instead of closer to the hut, though there is plenty of space.

![screenshot 2](https://cloud.githubusercontent.com/assets/18621498/14937305/ebbe0dfe-0f20-11e6-81ea-d5146c7ae6a1.png)

**Comment by andreas-eberle** [comment] 2016-05-01 08:41
The forester is planting a bit randomly by design. However, it prefers planting close to the center of its work area. If we let the forester plant in a circle from the center of its work area it looks really bad.

Did this happen very often or just once?

**Comment by derfuhrer2007** [comment] 2016-05-01 09:03
It is the first time I saw, found it a bit curious he was planting in a line and it was going all the way out

**Comment by andreas-eberle** [comment] 2016-05-01 11:17
OK, then I'll close this. This was just a random appearance.

**Closed by andreas-eberle** 2016-05-01 11:17 UTC
Labels: game logic
