### ISSUE TITLE
Explain how to support the project

### ISSUE THREAD

**Issue by krichter722** [jsettlers/settlers-remake#512] opened 2016-10-24 16:32 UTC
Add a hint to `CONTRIBUTING` or `README` about wanted support for the project (code, printed paper with defined value, coffee, beer, pizza, none, publicity).

**Comment by Hiradur** [comment] 2016-11-25 15:55
I think it would be a good idea to create a large list of issues of missing/unfinished features of the original engine under their own label (e.g. original engine feature). This would make it easier and less time consuming for contributors to spot places to work on.

**Comment by michaelzangl** [comment] 2016-11-25 16:28
We could use the relatively new Projects feature of github for this.

**Comment by michaelzangl** [comment] 2017-07-25 20:08
Duplicate of #163

**Closed by michaelzangl** 2017-07-25 20:08 UTC
