### ISSUE TITLE
Work area selection wrong

### ISSUE THREAD

**Issue by derfuhrer2007** [jsettlers/settlers-remake#465] opened 2016-05-26 18:41 UTC
I have selected exactly on the sawmill, however the selection was to the north. Did it again, same issue, it is way north than the sawmill area that I selected.

![screenshot 16](https://cloud.githubusercontent.com/assets/18621498/15585955/84b7fe7e-239f-11e6-8ad7-286c194b93d2.png)
[2016-05-26_23-22-52_Volcano_Mountain (3).zip](https://github.com/jsettlers/settlers-remake/files/285069/2016-05-26_23-22-52_Volcano_Mountain.3.zip)

**Comment by michaelzangl** [comment] 2016-05-26 20:14
Where was the work area before you clicked there?

**Comment by andreas-eberle** [comment] 2016-05-26 20:27
@michaelzangl: I think this is the same issue as #215. The problem is the calculated click position on high terrains.

**Comment by derfuhrer2007** [comment] 2016-05-26 23:06
Seems to be a problem when you give a target on a building. Observed this while moving troops.

@michaelzangl It was the default one

**Comment by andreas-eberle** [comment] 2018-04-02 21:59
Fixed with PR #672.

**Closed** 2018-04-02 21:59 UTC
Labels: bug (minor)
