### ISSUE TITLE
Barracks are giving me bowmen when i set Swords to high priority

### ISSUE THREAD

**Issue by Jayflux** [jsettlers/settlers-remake#228] opened 2015-11-05 00:08 UTC
see title

**Comment by codingberlin** [comment] 2015-11-05 05:58
This issue is a duplicate of #210. The status of issue #210 is, that it is implemented already in pull request #222 which just need to be merged and then you can influence the weapon production with the next release.

**Closed by codingberlin** 2015-11-05 05:58 UTC
