### ISSUE TITLE
Map creator window not shown

### ISSUE THREAD

**Issue by krichter722** [jsettlers/settlers-remake#204] opened 2015-10-15 17:22 UTC
Starting `java -jar MapCreator.jar` causes output

    Warning: Could not load LocaleSuffix [_en]. Falling back to next file.
    Warning: Could not load LocaleSuffix [_de_DE]. Falling back to next file.

but doesn't display any window.

experienced with v0.1.3-alpha-338-g09c8631

**Comment by andreasb242** [comment] 2016-01-17 15:10
In the new branch there a global error handling. If then still an error occur which prevent the window from showing, it will display an error.
So this should be solved when the branch is merged.

**Comment by andreas-eberle** [comment] 2016-01-18 23:04
@krichter722: Some questions:
* Did you start the game before (and select the folder with the gfx and snd folders)?
* Did you try to use ALT+Tab to see if the window switched to the background? The issue is that the first "window" is actually a dialog and therefore doesn't appear in the taskbar (where the program icons usually appear). Therefore it might happen that it switches into the background.

**Comment by andreasb242** [comment] 2016-01-24 11:24
This should be fixed with #299

**Comment by andreas-eberle** [comment] 2016-05-01 08:55
I also think this should be fixed with the new map editor UI. If it still exists, please reopen the ticket.

**Closed by andreas-eberle** 2016-05-01 08:55 UTC
